name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - name: Install openssl
      if: matrix.os == 'windows-latest'
      run: choco install openssl
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Release
      run: cargo build --verbose --release
    - name: Upload build artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: k8s-gcr-auth-helper-${{ matrix.os }}
        path: target/release/k8s-gcr-auth-helper
    - name: Upload build artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: k8s-gcr-auth-helper-${{ matrix.os }}
        path: target/release/k8s-gcr-auth-helper.exe
